/**
 * The library version this demos site uses.
 *
 * This is synced from the library repo's packages/core/package.json via
 * the sync-version.mjs script. When the library version changes, re-run:
 *   node scripts/sync-version.mjs
 *
 * DO NOT edit this file manually — it's auto-generated.
 */
export const LIBRARY_VERSION = '1.9.36';
